[project]
authors = ["Eric Sun <erictsun02@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Basketball"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
ultralytics = ">=8.3.86,<9"
numpy = ">=1.26.4,<2"
pip = ">=25.0.1,<26"
opencv = ">=4.11.0,<5"
pytorch = ">=2.6.0,<3"
torchvision = ">=0.21.0,<0.22"
ipdb = ">=0.13.13,<0.14"
filterpy = ">=1.4.5,<2"
scikit-image = ">=0.25.2,<0.26"
ruff = ">=0.9.10,<0.10"
black = ">=25.1.0,<26"
